

-----Original Message-----
--From: Chakri Adimulam 
--Sent: Friday, June 20, 2003 10:29 AM
--To: LeAnn Cole; Dipu_EDS (E-mail)
--Cc: BrianMcavoy_EDS (E-mail); MikkelHylden_EDS (E-mail); Clayton Royal
--Subject: SQL for Duplicate Payments report
--
--LeAnn/Dipu,
--
--Here is the SQL used for Duplicate Payments report.  This SQL uses RCOM tables copied to PRD1, if (in future) you like to change this to use DB links then just remove "TMP_" from RCOM table names.
--
--Thanks,
--Chakri
--



SELECT CUST.ACCOUNT_NUMBER CUSTOMER_NUMBER, ARC.ATTRIBUTE10 ORDER_NO, ARC.ATTRIBUTE11 PAYMENT_TP
   , TCOP.RCOM_ACCOUNT_OR_CHECK_NUMBER, TCOP.RCOM_RCPT_TOTAL_AMOUNT, SUM(ARC.AMOUNT) AR_RCPT_TOTAL_AMOUNT
   , (SUM(ARC.AMOUNT) - TCOP.RCOM_RCPT_TOTAL_AMOUNT) AR_RCOM_DIFFERENCE
FROM AR_CASH_RECEIPTS_ALL ARC
   , HZ_CUST_ACCOUNTS CUST
   , (SELECT OP.ORDER_NUMBER, NVL(OP.ACCOUNT_NUMBER, OP.CHECK_NUMBER) RCOM_ACCOUNT_OR_CHECK_NUMBER
         , SUM(OP.PAYMENT_AMOUNT) RCOM_RCPT_TOTAL_AMOUNT
      FROM TMP_COE_ORDER_PAYMENTS OP
      WHERE OP.PAYMENT_SETTLED_STATUS_CODE IN ('S', 'A')
      AND OP.PAYMENT_AMOUNT  > 0
      GROUP BY OP.ORDER_NUMBER, NVL(OP.ACCOUNT_NUMBER, OP.CHECK_NUMBER)) TCOP
WHERE ARC.ATTRIBUTE_CATEGORY = 'RCOM_INTERFACE' 
AND ARC.PAY_FROM_CUSTOMER = CUST.CUST_ACCOUNT_ID
AND ARC.STATUS IN ('APP', 'UNAPP')
AND ARC.ATTRIBUTE10 = TCOP.ORDER_NUMBER
AND INSTR(ARC.RECEIPT_NUMBER, TCOP.RCOM_ACCOUNT_OR_CHECK_NUMBER) > 0
GROUP BY CUST.ACCOUNT_NUMBER, ARC.ATTRIBUTE10, ARC.ATTRIBUTE11, TCOP.RCOM_ACCOUNT_OR_CHECK_NUMBER, TCOP.RCOM_RCPT_TOTAL_AMOUNT
HAVING TCOP.RCOM_RCPT_TOTAL_AMOUNT < SUM(ARC.AMOUNT)
ORDER BY (SUM(ARC.AMOUNT) - TCOP.RCOM_RCPT_TOTAL_AMOUNT) DESC, CUST.ACCOUNT_NUMBER, ARC.ATTRIBUTE10
   , ARC.ATTRIBUTE11, TCOP.RCOM_ACCOUNT_OR_CHECK_NUMBER;
